### PR TITLE
Fix size of bytes in write, use bytes from register, not from endpoint

### PR DESCRIPTION
**Pull request by MathiasMoog**
Dear Gideon,

I fixed a bug in the NumberEndpoint. If there are more than one Endpoints in a register, the size of the byte Array is wrong in the write Method.
Ich extended the code similar to the IntegerEndpoint and take the bytes from the register and not from the endpoint.

Best Regards

  Mathias

By the way, I have an extension for the panstamp-tools library, a Get value (query) similar to Set value. If you like I can send you the code fragment or create a pull request

### CODE REVIEW

**Comment by GideonLeGrange** [comment]
Hi Mathias

You're right, `NumberEndpoint.write` is incorrect. Thank you for picking this up and fixing it. 

I want to accept your pull request, but there is one problem. You've made `PanStamp.sendQueryMessage` public. It is part of the internals of the panstamp-java library and should not be public. If you need more functionality, I'll rather figure out how to adapt the public interface to address that. 

Can you please remove the commits after `d7aed64` from the pull request so I can accept it? 

Many thanks
Gideon

**Comment by GideonLeGrange** [comment]
Closing. Thanks @MathiasMoog for pointing the out the problem with `NumberEndpoint`. I fixed the code independently, I don't want to merge in the other changes in this PR.

**Comment by MathiasMoog** [comment]
Hi Gideon,

sorry for the late answer, your mail got lost in my spam folder.

You are right, the fix is only in NumberEndpoint.

It was the first time I worked on github and it was not clear to me that
I should avoid additional checkins on this branch.

The additional changes correspond to an "Get Data" Extension. I add "Get
Data" Entries to all Menues where a "Set Data" appears. It sends a query
to a device and the device reports the state. I found it useful for
testing my panstamp implementations.
For this extension is need access to method which send a query to a
specific device. My solution was to change the sendQueryMessage to
public, but perhaps you have an better idea.

Best regards

  Mathias


Am 24.01.2016 um 22:30 schrieb Gideon le Grange:

**Comment by GideonLeGrange** [comment]
> On 15 Feb 2016, at 22:34, Mathias Moog <notifications@github.com> wrote:
> 
> The additional changes correspond to an "Get Data" Extension. I add "Get
> Data" Entries to all Menues where a "Set Data" appears. It sends a query
> to a device and the device reports the state. I found it useful for
> testing my panstamp implementations.
> For this extension is need access to method which send a query to a
> specific device. My solution was to change the sendQueryMessage to
> public, but perhaps you have an better idea.

Hi Mathias 

I can see the point to what you want, especially if you have mains powered devices that don’t sleep, or for development purposes. 

So what I think we can do is to add a requestValue() method to Endpoint and to Register (so that it’s available where a user could conceivably want to use it). This doesn’t expose the internals of the PanStamp class and the user doesn’t need to understand the SWAP stack that well - he can use the instance of Endpoint or Register that he will be attaching his listeners to or calling hasValue() / getValue() on. 

I’ve implemented what I describe above in the ‘request’ branch. Can you please check it out and let me know if that will work for you? If it looks good, I’ll merge it into master and release panstamp-java 2.2.

Kind regards
Gideon

**Comment by MathiasMoog** [comment]
Hi Gideon, 

it works fine for me. It woud be creat if you add it to the next version.

Best regards

  Mathias

**Comment by GideonLeGrange** [comment]
Hi Mathias

Thank you. I’ve added it and released new versions of panstamp-java and panstamp-tools

G

**Pull request closed without merging**
